# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aligndialog_base.ui'
#
# Created: Thu Jul 30 10:31:01 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 568)
        self.gridlayout = QtGui.QGridLayout(Dialog)
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 3)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridlayout.addWidget(self.line, 1, 0, 1, 5)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridlayout.addWidget(self.line_2, 3, 0, 1, 5)
        self.StepText = QtGui.QLabel(Dialog)
        self.StepText.setObjectName("StepText")
        self.gridlayout.addWidget(self.StepText, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(191, 29, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 4, 1, 1, 1)
        self.NextButton = QtGui.QPushButton(Dialog)
        self.NextButton.setObjectName("NextButton")
        self.gridlayout.addWidget(self.NextButton, 4, 3, 1, 1)
        self.CancelButton = QtGui.QPushButton(Dialog)
        self.CancelButton.setObjectName("CancelButton")
        self.gridlayout.addWidget(self.CancelButton, 4, 4, 1, 1)
        self.StackedWidget = QtGui.QStackedWidget(Dialog)
        self.StackedWidget.setObjectName("StackedWidget")
        self.StartPage = QtGui.QWidget()
        self.StartPage.setObjectName("StartPage")
        self.gridlayout1 = QtGui.QGridLayout(self.StartPage)
        self.gridlayout1.setObjectName("gridlayout1")
        self.DeviceComboBox = DeviceUriComboBox(self.StartPage)
        self.DeviceComboBox.setObjectName("DeviceComboBox")
        self.gridlayout1.addWidget(self.DeviceComboBox, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.StartPage)
        self.groupBox.setObjectName("groupBox")
        self.gridlayout2 = QtGui.QGridLayout(self.groupBox)
        self.gridlayout2.setObjectName("gridlayout2")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridlayout2.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridlayout1.addWidget(self.groupBox, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(564, 161, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem1, 2, 0, 1, 1)
        self.StackedWidget.addWidget(self.StartPage)
        self.LoadPaperPage = QtGui.QWidget()
        self.LoadPaperPage.setObjectName("LoadPaperPage")
        self.gridlayout3 = QtGui.QGridLayout(self.LoadPaperPage)
        self.gridlayout3.setObjectName("gridlayout3")
        self.LoadPaper = LoadPaperGroupBox(self.LoadPaperPage)
        self.LoadPaper.setObjectName("LoadPaper")
        self.gridlayout3.addWidget(self.LoadPaper, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 181, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout3.addItem(spacerItem2, 1, 0, 1, 1)
        self.StackedWidget.addWidget(self.LoadPaperPage)
        self.PaperEdgePage = QtGui.QWidget()
        self.PaperEdgePage.setObjectName("PaperEdgePage")
        self.gridlayout4 = QtGui.QGridLayout(self.PaperEdgePage)
        self.gridlayout4.setObjectName("gridlayout4")
        self.PageEdgeTitle = QtGui.QLabel(self.PaperEdgePage)
        self.PageEdgeTitle.setObjectName("PageEdgeTitle")
        self.gridlayout4.addWidget(self.PageEdgeTitle, 0, 0, 1, 4)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout4.addItem(spacerItem3, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout4.addItem(spacerItem4, 2, 0, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.PageEdgeIcon = QtGui.QLabel(self.PaperEdgePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PageEdgeIcon.sizePolicy().hasHeightForWidth())
        self.PageEdgeIcon.setSizePolicy(sizePolicy)
        self.PageEdgeIcon.setMinimumSize(QtCore.QSize(85, 90))
        self.PageEdgeIcon.setMaximumSize(QtCore.QSize(85, 90))
        self.PageEdgeIcon.setFrameShape(QtGui.QFrame.NoFrame)
        self.PageEdgeIcon.setObjectName("PageEdgeIcon")
        self.hboxlayout.addWidget(self.PageEdgeIcon)
        self.PageEdgeComboBox = QtGui.QComboBox(self.PaperEdgePage)
        self.PageEdgeComboBox.setObjectName("PageEdgeComboBox")
        self.hboxlayout.addWidget(self.PageEdgeComboBox)
        self.gridlayout4.addLayout(self.hboxlayout, 2, 1, 1, 2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout4.addItem(spacerItem5, 2, 3, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout4.addItem(spacerItem6, 3, 2, 1, 1)
        self.StackedWidget.addWidget(self.PaperEdgePage)
        self.AlignmentNumber = QtGui.QWidget()
        self.AlignmentNumber.setObjectName("AlignmentNumber")
        self.gridlayout5 = QtGui.QGridLayout(self.AlignmentNumber)
        self.gridlayout5.setObjectName("gridlayout5")
        self.AlignmentNumberTitle = QtGui.QLabel(self.AlignmentNumber)
        self.AlignmentNumberTitle.setObjectName("AlignmentNumberTitle")
        self.gridlayout5.addWidget(self.AlignmentNumberTitle, 0, 0, 1, 4)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout5.addItem(spacerItem7, 1, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout5.addItem(spacerItem8, 2, 0, 1, 1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.AlignmentNumberIcon = QtGui.QLabel(self.AlignmentNumber)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AlignmentNumberIcon.sizePolicy().hasHeightForWidth())
        self.AlignmentNumberIcon.setSizePolicy(sizePolicy)
        self.AlignmentNumberIcon.setMinimumSize(QtCore.QSize(85, 90))
        self.AlignmentNumberIcon.setMaximumSize(QtCore.QSize(85, 90))
        self.AlignmentNumberIcon.setFrameShape(QtGui.QFrame.NoFrame)
        self.AlignmentNumberIcon.setObjectName("AlignmentNumberIcon")
        self.hboxlayout1.addWidget(self.AlignmentNumberIcon)
        self.AlignmentNumberComboBox = QtGui.QComboBox(self.AlignmentNumber)
        self.AlignmentNumberComboBox.setObjectName("AlignmentNumberComboBox")
        self.hboxlayout1.addWidget(self.AlignmentNumberComboBox)
        self.gridlayout5.addLayout(self.hboxlayout1, 2, 1, 1, 2)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout5.addItem(spacerItem9, 2, 3, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout5.addItem(spacerItem10, 3, 2, 1, 1)
        self.StackedWidget.addWidget(self.AlignmentNumber)
        self.ColorAdjPage = QtGui.QWidget()
        self.ColorAdjPage.setObjectName("ColorAdjPage")
        self.gridlayout6 = QtGui.QGridLayout(self.ColorAdjPage)
        self.gridlayout6.setObjectName("gridlayout6")
        self.label_12 = QtGui.QLabel(self.ColorAdjPage)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.gridlayout6.addWidget(self.label_12, 0, 0, 1, 5)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout6.addItem(spacerItem11, 1, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout6.addItem(spacerItem12, 2, 0, 1, 1)
        self.ColorAdjustIcon = QtGui.QLabel(self.ColorAdjPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorAdjustIcon.sizePolicy().hasHeightForWidth())
        self.ColorAdjustIcon.setSizePolicy(sizePolicy)
        self.ColorAdjustIcon.setMinimumSize(QtCore.QSize(85, 90))
        self.ColorAdjustIcon.setMaximumSize(QtCore.QSize(85, 90))
        self.ColorAdjustIcon.setFrameShape(QtGui.QFrame.NoFrame)
        self.ColorAdjustIcon.setObjectName("ColorAdjustIcon")
        self.gridlayout6.addWidget(self.ColorAdjustIcon, 2, 1, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(31, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout6.addItem(spacerItem13, 2, 2, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.ColorAdjustLabel = QtGui.QLabel(self.ColorAdjPage)
        self.ColorAdjustLabel.setObjectName("ColorAdjustLabel")
        self.hboxlayout2.addWidget(self.ColorAdjustLabel)
        self.ColorAdjustComboBox = QtGui.QComboBox(self.ColorAdjPage)
        self.ColorAdjustComboBox.setObjectName("ColorAdjustComboBox")
        self.hboxlayout2.addWidget(self.ColorAdjustComboBox)
        self.gridlayout6.addLayout(self.hboxlayout2, 2, 3, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout6.addItem(spacerItem14, 2, 4, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout6.addItem(spacerItem15, 3, 1, 1, 1)
        self.StackedWidget.addWidget(self.ColorAdjPage)
        self.LBowPage = QtGui.QWidget()
        self.LBowPage.setObjectName("LBowPage")
        self.gridlayout7 = QtGui.QGridLayout(self.LBowPage)
        self.gridlayout7.setObjectName("gridlayout7")
        self.LBowTitle = QtGui.QLabel(self.LBowPage)
        self.LBowTitle.setWordWrap(True)
        self.LBowTitle.setObjectName("LBowTitle")
        self.gridlayout7.addWidget(self.LBowTitle, 0, 0, 1, 5)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout7.addItem(spacerItem16, 1, 1, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(41, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem17, 2, 0, 1, 1)
        self.LBowIcon = QtGui.QLabel(self.LBowPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBowIcon.sizePolicy().hasHeightForWidth())
        self.LBowIcon.setSizePolicy(sizePolicy)
        self.LBowIcon.setMinimumSize(QtCore.QSize(192, 93))
        self.LBowIcon.setMaximumSize(QtCore.QSize(192, 93))
        self.LBowIcon.setFrameShape(QtGui.QFrame.NoFrame)
        self.LBowIcon.setObjectName("LBowIcon")
        self.gridlayout7.addWidget(self.LBowIcon, 2, 1, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem18, 2, 2, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout7.addItem(spacerItem19, 2, 4, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout7.addItem(spacerItem20, 3, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.LBowPage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridlayout8 = QtGui.QGridLayout(self.groupBox_2)
        self.gridlayout8.setObjectName("gridlayout8")
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.hboxlayout3.addWidget(self.label_4)
        self.aComboBox = QtGui.QComboBox(self.groupBox_2)
        self.aComboBox.setObjectName("aComboBox")
        self.hboxlayout3.addWidget(self.aComboBox)
        self.gridlayout8.addLayout(self.hboxlayout3, 0, 0, 1, 1)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.hboxlayout4.addWidget(self.label_5)
        self.bComboBox = QtGui.QComboBox(self.groupBox_2)
        self.bComboBox.setObjectName("bComboBox")
        self.hboxlayout4.addWidget(self.bComboBox)
        self.gridlayout8.addLayout(self.hboxlayout4, 1, 0, 1, 1)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.hboxlayout5.addWidget(self.label_6)
        self.cComboBox = QtGui.QComboBox(self.groupBox_2)
        self.cComboBox.setObjectName("cComboBox")
        self.hboxlayout5.addWidget(self.cComboBox)
        self.gridlayout8.addLayout(self.hboxlayout5, 2, 0, 1, 1)
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.hboxlayout6.addWidget(self.label_7)
        self.dComboBox = QtGui.QComboBox(self.groupBox_2)
        self.dComboBox.setObjectName("dComboBox")
        self.hboxlayout6.addWidget(self.dComboBox)
        self.gridlayout8.addLayout(self.hboxlayout6, 3, 0, 1, 1)
        self.hboxlayout7 = QtGui.QHBoxLayout()
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.hboxlayout7.addWidget(self.label_8)
        self.eComboBox = QtGui.QComboBox(self.groupBox_2)
        self.eComboBox.setObjectName("eComboBox")
        self.hboxlayout7.addWidget(self.eComboBox)
        self.gridlayout8.addLayout(self.hboxlayout7, 4, 0, 1, 1)
        self.hboxlayout8 = QtGui.QHBoxLayout()
        self.hboxlayout8.setObjectName("hboxlayout8")
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.hboxlayout8.addWidget(self.label_9)
        self.fComboBox = QtGui.QComboBox(self.groupBox_2)
        self.fComboBox.setObjectName("fComboBox")
        self.hboxlayout8.addWidget(self.fComboBox)
        self.gridlayout8.addLayout(self.hboxlayout8, 5, 0, 1, 1)
        self.hboxlayout9 = QtGui.QHBoxLayout()
        self.hboxlayout9.setObjectName("hboxlayout9")
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.hboxlayout9.addWidget(self.label_10)
        self.gComboBox = QtGui.QComboBox(self.groupBox_2)
        self.gComboBox.setObjectName("gComboBox")
        self.hboxlayout9.addWidget(self.gComboBox)
        self.gridlayout8.addLayout(self.hboxlayout9, 6, 0, 1, 1)
        self.hboxlayout10 = QtGui.QHBoxLayout()
        self.hboxlayout10.setObjectName("hboxlayout10")
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.hboxlayout10.addWidget(self.label_11)
        self.hComboBox = QtGui.QComboBox(self.groupBox_2)
        self.hComboBox.setObjectName("hComboBox")
        self.hboxlayout10.addWidget(self.hComboBox)
        self.gridlayout8.addLayout(self.hboxlayout10, 7, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.iComboBox = QtGui.QComboBox(self.groupBox_2)
        self.iComboBox.setObjectName("iComboBox")
        self.horizontalLayout.addWidget(self.iComboBox)
        self.gridlayout8.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.gridlayout7.addWidget(self.groupBox_2, 1, 3, 3, 1)
        self.StackedWidget.addWidget(self.LBowPage)
        self.AioPage = QtGui.QWidget()
        self.AioPage.setObjectName("AioPage")
        self.gridlayout9 = QtGui.QGridLayout(self.AioPage)
        self.gridlayout9.setObjectName("gridlayout9")
        spacerItem21 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout9.addItem(spacerItem21, 0, 1, 1, 1)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout9.addItem(spacerItem22, 1, 0, 1, 1)
        self.AioIcon = QtGui.QLabel(self.AioPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AioIcon.sizePolicy().hasHeightForWidth())
        self.AioIcon.setSizePolicy(sizePolicy)
        self.AioIcon.setMinimumSize(QtCore.QSize(92, 120))
        self.AioIcon.setMaximumSize(QtCore.QSize(92, 120))
        self.AioIcon.setFrameShape(QtGui.QFrame.NoFrame)
        self.AioIcon.setObjectName("AioIcon")
        self.gridlayout9.addWidget(self.AioIcon, 1, 1, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout9.addItem(spacerItem23, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.AioPage)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridlayout9.addWidget(self.label_3, 1, 3, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout9.addItem(spacerItem24, 2, 1, 1, 1)
        self.StackedWidget.addWidget(self.AioPage)
        self.FrontPanelPage = QtGui.QWidget()
        self.FrontPanelPage.setObjectName("FrontPanelPage")
        self.gridlayout10 = QtGui.QGridLayout(self.FrontPanelPage)
        self.gridlayout10.setObjectName("gridlayout10")
        self.label_13 = QtGui.QLabel(self.FrontPanelPage)
        self.label_13.setTextFormat(QtCore.Qt.RichText)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.gridlayout10.addWidget(self.label_13, 0, 0, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout10.addItem(spacerItem25, 1, 0, 1, 1)
        self.StackedWidget.addWidget(self.FrontPanelPage)
        self.gridlayout.addWidget(self.StackedWidget, 2, 0, 1, 5)

        self.retranslateUi(Dialog)
        self.StackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "HP Device Manager - Align Print Cartridges", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Align Print Cartridges", None, QtGui.QApplication.UnicodeUTF8))
        self.StepText.setText(QtGui.QApplication.translate("Dialog", "Step %1 of %2", None, QtGui.QApplication.UnicodeUTF8))
        self.NextButton.setText(QtGui.QApplication.translate("Dialog", "Next >", None, QtGui.QApplication.UnicodeUTF8))
        self.CancelButton.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select the device to align and click <span style=\" font-style:italic;\">Next &gt;</span> to continue.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Choose the numbered colored box that the color <b>best </b>matches the background color of the bar.", None, QtGui.QApplication.UnicodeUTF8))
        self.ColorAdjustLabel.setText(QtGui.QApplication.translate("Dialog", "Line %1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Row A:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Row B:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Row C:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Row D:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Row E:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Row F:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Row G:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Row H:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Row I:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Follow these steps to complete the alignment:</span> </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">1.</span> Place the alignment page, with the printed side facing down, on the scanner. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">2.</span> Press the <span style=\" font-style:italic;\">Enter</span> or <span style=\" font-style:italic;\">Scan</span> button on the printer. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">3.</span> \"Alignment Complete\" will be displayed when the process is finished (on some models with a front panel display) or the green light that was blinking during the process will stop blinking and remain green (on some models without a front panel display).</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Cartridge alignment on this printer is only available by accessing the front panel of the printer. </span>Please refer to the user guide for the printer for more information. Click <span style=\" font-style:italic;\">Finish</span> to exit.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

from loadpapergroupbox import LoadPaperGroupBox
from deviceuricombobox import DeviceUriComboBox
